preprocess:
  input: data/raw/Social_Network_Ads.csv
  output: data/processed/Social_Network_Ads_processed.csv

train:
  input: data/processed/Social_Network_Ads_processed.csv
  output: models/model.pkl
  test_size: 0.2
  random_state: 42
  n_estimators: [100,200]
  max_depth: [2,5]